### ISSUE TITLE
Application: Failed to retrieve application JMX service URL.

### ISSUE THREAD

**Issue by Bk24MamBa** [halo-dev/halo#229]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [ x] [Halo 使用文档](https://halo.run/docs)
- [ x] [Halo 论坛](https://bbs.halo.run)
- [ ] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [ ] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

Application: Failed to retrieve application JMX service URL.
运行时有显示.listener.StartedListener    : Halo started at         http://10.201.30.243:8090
2019-07-02 19:45:52.623  INFO 11836 --- [  restartedMain] run.halo.app.listener.StartedListener    : Halo admin started at   http://10.201.30.243:8090/admin
但是输入网页不能正常打开  event log提示Application: Failed to retrieve application JMX service URL   问题是出在哪里啊，需要怎么解决该问题呢  谢谢！

**Comment by ruibaby** [comment]
你这个问题确实还没遇到过，我们尝试复现一下。

**Comment by ruibaby** [comment]
能提供一下你的配置信息吗？还有详细的日志，我没有办法复现这个问题。

**Comment by ChannD** [comment]
IDEA

Starting from 2018.3.4 IntelliJ IDEA use local JMX connector for retrieving Spring Boot actuator endpoint's data. Local JMX monitoring has some restrictions, in particular, it isn't possible to get local JMX connector address if Spring Boot application and IntelliJ IDEA JVMs have different bitness. If it is not possible to run application on JVM with the same bitness, then, in order to fix the problem, one could add the following to Spring Boot run configuration's VM options:

`-Dcom.sun.management.jmxremote.port={some_port} -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false
`
